READINGS_URL = "READINGS_URL"
READINGS_HEADERS = "READINGS_HEADERS"

FORECAST_URL = "FORECAST_URL"
FORECAST_HEADERS = "FORECAST_HEADERS"

SUBJECT = "SUBJECT"
FROM_COMPANY = "FROM_COMPANY"
FROM = "FROM"
TO = "TO"
BCC = "BCC"

SMTP_EMAIL = "SMTP_EMAIL"
SMTP_PORT = "SMTP_PORT"
SMTP_PASSWORD = "SMTP_PASSWORD"

ACCOUNT_SID = "ACCOUNT_SID"
AUTH_TOKEN = "AUTH_TOKEN"
MESSAGING_SERVICE_ID = "MESSAGING_SERVICE_ID"
TO_NUMBER = "TO_NUMBER"